# Generated by Django 2.0.12 on 2019-07-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpsInfo',
        ),
    ]
