# Generated by Django 2.0.12 on 2019-07-11 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mgsd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpAgentCfgInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('snmp_port', models.IntegerField(default=161, verbose_name='Snmp端口')),
                ('snmp_community', models.CharField(max_length=32, verbose_name='Snmp组织密码')),
                ('collected', models.BooleanField(default=True, verbose_name='是否收集')),
                ('cop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_cfg_of_cop', to='mgsd.SysManagerCopInfo', verbose_name='平台中的系统部件')),
            ],
            options={
                'verbose_name': 'Snmp配置信息',
                'db_table': 'snmp_agent_cfg_info',
            },
        ),
        migrations.CreateModel(
            name='SnmpHostData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('send_flow', models.FloatField(default=0.0, verbose_name='发送的字节数')),
                ('recv_flow', models.FloatField(default=0.0, verbose_name='接受字节数')),
                ('cpu_percent', models.FloatField(default=0.0, verbose_name='CPU占用')),
                ('mem_percent', models.FloatField(default=0.0, verbose_name='内存占用')),
                ('disk_percent', models.FloatField(default=0.0, verbose_name='硬盘占用')),
                ('up_time', models.IntegerField(blank=True, default=0, verbose_name='开启时间')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='监控时间')),
                ('cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_data_of_cop', to='mgsd.SysManagerCopInfo', verbose_name='平台中的系统部件')),
            ],
            options={
                'verbose_name': 'SNMP部件监控数据',
                'db_table': 'snmp_agent_data',
                'ordering': ('-date_created',),
            },
        ),
    ]
