# Generated by Django 2.0.12 on 2019-07-26 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scheme', models.CharField(default='http://localhost:8000', max_length=200, verbose_name='URL前缀')),
                ('url', models.CharField(default='/', max_length=200, verbose_name='URL')),
                ('data', models.CharField(default='', max_length=255, verbose_name='payload')),
                ('method', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE'), ('option', 'OPTION')], max_length=100, verbose_name='进程类型')),
                ('auth', models.BooleanField(default=True, verbose_name='需要认证')),
                ('params', models.CharField(default='', max_length=255, verbose_name='请求参数')),
                ('name', models.CharField(default='', max_length=255, verbose_name='API名称')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='API描述')),
                ('type', models.CharField(default='', max_length=255, verbose_name='API类型')),
                ('response', models.CharField(default='', max_length=255, verbose_name='响应描述')),
                ('example', models.CharField(default='', max_length=255, verbose_name='使用举例')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cop_api', to='mgsd.SysManagerCopInfo', verbose_name='部件')),
            ],
            options={
                'verbose_name': '特定的运行进程',
                'db_table': 'agent_api',
            },
        ),
    ]
