# Generated by Django 2.0.12 on 2019-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentapi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentapi',
            options={'verbose_name': '系统部件的API'},
        ),
        migrations.RenameField(
            model_name='agentapi',
            old_name='type',
            new_name='_type',
        ),
        migrations.RemoveField(
            model_name='agentapi',
            name='response',
        ),
        migrations.AddField(
            model_name='agentapi',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='API修改时间'),
        ),
        migrations.AddField(
            model_name='agentapi',
            name='error_eg',
            field=models.CharField(default='', max_length=255, verbose_name='错误响应举例'),
        ),
        migrations.AddField(
            model_name='agentapi',
            name='response_eg',
            field=models.CharField(default='', max_length=255, verbose_name='响应举例'),
        ),
    ]
