# Generated by Django 2.0.12 on 2019-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20190726_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentapi',
            old_name='scheme',
            new_name='prefix',
        ),
    ]
