# Generated by Django 2.0.12 on 2019-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeaudit',
            name='remote_addr',
            field=models.GenericIPAddressField(default='127.0.0.1', help_text='操作的IP', verbose_name='IP'),
        ),
    ]
