# Generated by Django 2.0.12 on 2019-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0002_auto_20190705_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systempolicycentralizedmanagement',
            name='cop',
        ),
        migrations.RemoveField(
            model_name='systempolicycentralizedmanagement',
            name='sources',
        ),
    ]
