# Generated by Django 2.0.12 on 2019-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0002_changeaudit_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogobject',
            name='showd',
            field=models.BooleanField(default=True, verbose_name='展示'),
        ),
    ]
