# Generated by Django 2.0.12 on 2019-07-08 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0003_auto_20190705_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChangeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '审计变更管理',
            },
        ),
        migrations.CreateModel(
            name='AuditEventResponseSolve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '审计事件响应处置',
            },
        ),
        migrations.CreateModel(
            name='AuditPolicyCentralizedManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '审计策略集中管理',
            },
        ),
        migrations.CreateModel(
            name='AuditPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '审计管理策略',
            },
        ),
        migrations.CreateModel(
            name='SecurityChangeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '安全变更管理',
            },
        ),
        migrations.CreateModel(
            name='SecurityEventResponseSolve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '安全事件响应处置',
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicyCentralizedManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '安全策略集中管理',
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '安全管理策略',
            },
        ),
        migrations.CreateModel(
            name='SystemChangeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '系统变更管理',
            },
        ),
        migrations.CreateModel(
            name='SystemEventResponseSolve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '系统事件响应处置',
            },
        ),
        migrations.CreateModel(
            name='SystemPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '系统管理策略',
            },
        ),
        migrations.AlterModelOptions(
            name='backuphistory',
            options={'ordering': ('-date_created',), 'verbose_name': '系统备份'},
        ),
        migrations.AddField(
            model_name='infosecevent',
            name='plat_etype',
            field=models.CharField(choices=[('system', '系统管理策略'), ('security', '安全机制策略'), ('audit', '审计机制策略')], default='system', max_length=50, verbose_name='平台故障事件分类'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='pushed',
            field=models.BooleanField(default=False, verbose_name='接入'),
        ),
        migrations.AlterModelTable(
            name='systempolicycentralizedmanagement',
            table=None,
        ),
    ]
