# Generated by Django 2.0.12 on 2019-07-11 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0003_auditlogobject_showd'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMgQuerySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('log_expire', models.IntegerField(default=200, verbose_name='日志有效期')),
                ('log_max_free', models.FloatField(default=200.5, verbose_name='日志最小空闲值')),
                ('log_max_used', models.FloatField(default=700.5, verbose_name='日志最大使用值')),
                ('solve', models.CharField(choices=[('Clear', '清理日志'), ('Alert', '仅告警和通知管理员'), ('C&A', '清理日志并通知管理员')], default='C&A', max_length=33, verbose_name='设置日志到达阈值的处理措施')),
                ('auto_backup', models.BooleanField(default=False, verbose_name='是否自动备份')),
                ('default_backup_crontab', models.CharField(default='每周一 1:0', max_length=55, verbose_name='备份时间描述')),
                ('default_backup_path', models.CharField(default='/srv/data/log', max_length=55, verbose_name='默认本地备份位置')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '日志管理',
                'db_table': 'log_mg',
            },
        ),
        migrations.CreateModel(
            name='PasswordQuerySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, verbose_name='密码名称')),
                ('desc', models.CharField(max_length=55, verbose_name='密码名称')),
                ('rgx', models.CharField(max_length=255, verbose_name='密码正则')),
                ('active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '密码安全管理',
                'db_table': 'password_selected',
            },
        ),
        migrations.AlterField(
            model_name='connectmanageruserinfo',
            name='_identity',
            field=models.CharField(choices=[('sysuser', '非特权系统管理员'), ('secuser', '安全管理员'), ('auduser', '审计管理员'), ('superuser', '特权管理员')], default='superuser', max_length=66, verbose_name='部件管理身份'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='plat_username',
            field=models.CharField(blank=True, max_length=55, verbose_name='关联的平台用户'),
        ),
    ]
