# Generated by Django 2.0.12 on 2019-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0004_auto_20190708_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosecevent',
            name='effect_info',
            field=models.ManyToManyField(blank=True, default=None, related_name='info_conn_effect', to='mgsd.EffectInfo', verbose_name='负面影响'),
        ),
        migrations.AlterField(
            model_name='infosecevent',
            name='impact_cops',
            field=models.ManyToManyField(blank=True, related_name='info_conn_cops', to='mgsd.SysManagerCopInfo', verbose_name='受影响的资产列表'),
        ),
    ]
