# Generated by Django 2.0.12 on 2019-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0005_auto_20190708_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogobject',
            name='process',
        ),
        migrations.AddField(
            model_name='auditlogobject',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='audit_conn_users', to='mgsd.ConnectManagerUserInfo', verbose_name='审计管理用户'),
        ),
        migrations.AddField(
            model_name='auditlogobject',
            name='table_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='表名'),
        ),
    ]
