# Generated by Django 2.0.12 on 2019-07-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0006_auto_20190708_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogobject',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='infosecevent',
            name='info_source',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_source', to='mgsd.SysManagerCopInfo', verbose_name='信息来源'),
        ),
    ]
