# Generated by Django 2.0.12 on 2019-07-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0007_auto_20190709_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosecevent',
            name='info_source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_source', to='mgsd.SysManagerCopInfo', verbose_name='信息来源'),
        ),
    ]
