# Generated by Django 2.0.12 on 2019-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsd', '0008_auto_20190709_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosecevent',
            name='extra',
            field=models.CharField(default='', max_length=200, verbose_name='额外补充字段'),
        ),
    ]
