# Generated by Django 2.0.12 on 2019-06-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='部件接入时间'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='部件信息修改时间'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='extra',
            field=models.TextField(blank=True, verbose_name='额外补充信息'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='level',
            field=models.CharField(choices=[('High', '高'), ('Midium', '中'), ('Low', '低')], default='High', max_length=128, verbose_name='安全等级'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='sys_cop_conn_users', to='server.ConnectManagerUserInfo', verbose_name='系统部件管理用户'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='type',
            field=models.CharField(choices=[('CommonServer', '普通服务器、终端设备操作系统'), ('ServerDb', '服务器数据库管理系统'), ('ServerDb', '应用软件系统'), ('Netd', '路由器交换机网络设备'), ('Firewalld', '防火墙系统'), ('IDS/IPS', '入侵检测/防御系统'), ('MISP', '统一威胁管理系统'), ('Gelid', '网络和终端隔离设备'), ('NetdWorkDivice', '联网办公设备'), ('NetdPhisicalDivice', '联网的物理安全设施'), ('Others', '其他')], max_length=128, verbose_name='系统部件的类型'),
        ),
    ]
