# Generated by Django 2.0.12 on 2019-06-20 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosecevent',
            name='impact_area',
        ),
        migrations.AddField(
            model_name='policyrule',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='opreate_username',
            field=models.CharField(default='plat', max_length=33, verbose_name='备份用户'),
        ),
        migrations.AlterField(
            model_name='changeaudit',
            name='opreate_username',
            field=models.CharField(help_text='默认为操作员', max_length=33, verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='infosecevent',
            name='info_level',
            field=models.IntegerField(choices=[(1, '一般'), (2, '重大'), (3, '特别重大')], default=1, verbose_name='安全等级'),
        ),
        migrations.AlterField(
            model_name='infosecevent',
            name='info_type',
            field=models.CharField(choices=[('attack', '攻击事件'), ('bug', '故障事件'), ('destory', '灾害事件')], default='attack', max_length=50, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='infosecevent',
            name='infosysname',
            field=models.CharField(default='self', max_length=100, verbose_name='信息来源'),
        ),
        migrations.AlterField(
            model_name='policyaction',
            name='belong_cop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cop_policy_conn', to='server.SysManagerCopInfo', verbose_name='部件应用'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='belong_cop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rule_cop', to='server.SysManagerCopInfo', verbose_name='部件应用'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='policy_bench',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_bench_rule', to='server.PolicyBench', verbose_name='策略基准'),
        ),
    ]
