# Generated by Django 2.0.12 on 2019-06-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190622_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosecevent',
            name='infosysname',
            field=models.CharField(default='', max_length=200, verbose_name='事件名称'),
        ),
        migrations.AlterField(
            model_name='sysmanagercopinfo',
            name='type',
            field=models.CharField(choices=[('CommonServer', '普通服务器、终端设备操作系统'), ('ServerDb', '服务器数据库管理系统'), ('Softd', '应用软件系统'), ('Openvas', '网络脆弱性扫描系统'), ('Netd', '路由器交换机网络设备'), ('Firewalld', '防火墙系统'), ('IDS/IPS', '入侵检测/防御系统'), ('MISP', '统一威胁管理系统'), ('Gelid', '网络和终端隔离设备'), ('NetdWorkDivice', '联网办公设备'), ('NetdPhisicalDivice', '联网的物理安全设施'), ('Others', '其他')], max_length=128, verbose_name='系统部件的类型'),
        ),
    ]
