# Generated by Django 2.0.12 on 2019-06-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogoin',
            name='go_user',
            field=models.CharField(max_length=33, verbose_name='处理用户'),
        ),
        migrations.AlterField(
            model_name='objprocess',
            name='process_type',
            field=models.CharField(choices=[('system', '系统管理策略'), ('security', '安全机制策略'), ('audit', '审计机制策略')], max_length=100, verbose_name='进程类型'),
        ),
        migrations.AlterField(
            model_name='policybench',
            name='type',
            field=models.CharField(choices=[('system', '系统管理策略'), ('security', '安全机制策略'), ('audit', '审计机制策略')], max_length=50, verbose_name='基准类型'),
        ),
    ]
