# Generated by Django 2.0.12 on 2019-06-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190622_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogobject',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cop_audit_process', to='server.ObjProcess', verbose_name='审计对象进程指定'),
        ),
        migrations.AlterField(
            model_name='policyactionhistory',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下发时间'),
        ),
    ]
