# Generated by Django 2.0.12 on 2019-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190621_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeaudit',
            name='change_object',
        ),
        migrations.RemoveField(
            model_name='changeaudit',
            name='change_subject',
        ),
        migrations.AddField(
            model_name='changeaudit',
            name='change_name',
            field=models.CharField(blank=True, default=None, max_length=155, verbose_name='变更名'),
        ),
        migrations.AddField(
            model_name='changeaudit',
            name='change_obj',
            field=models.CharField(blank=True, default=None, max_length=155, verbose_name='变更对象'),
        ),
        migrations.AddField(
            model_name='changeaudit',
            name='change_type',
            field=models.CharField(choices=[('system', '系统管理策略'), ('security', '安全机制策略'), ('audit', '审计机制策略')], default='system', max_length=33, verbose_name='变更类型'),
        ),
        migrations.AlterField(
            model_name='changeaudit',
            name='change_desc',
            field=models.CharField(blank=True, default=None, max_length=155, verbose_name='变更描述'),
        ),
        migrations.AlterField(
            model_name='changeaudit',
            name='change_stat',
            field=models.CharField(choices=[('APPENDING', '变更中'), ('FAILED', '变更失败'), ('SECCUSS', '变更成功'), ('ROLLING', '变更回滚')], default='SECCUSS', max_length=10, verbose_name='变更状态'),
        ),
    ]
