# Generated by Django 2.0.12 on 2019-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190624_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmanageruserinfo',
            name='create_user',
            field=models.CharField(default='admin001', max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='connectmanageruserinfo',
            name='email',
            field=models.CharField(default='test@example.com', max_length=100, verbose_name='默认登记邮箱'),
        ),
    ]
