# Generated by Django 2.0.12 on 2019-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190624_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmanageruserinfo',
            name='_identity',
            field=models.CharField(choices=[('sysuser', '系统管理员'), ('secuser', '安全管理员'), ('auduser', '审计管理员'), ('superuser', '特权管理员')], default='superuser', max_length=66, verbose_name='部件管理身份'),
        ),
        migrations.AlterField(
            model_name='connectmanageruserinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='connectmanageruserinfo',
            name='name',
            field=models.CharField(max_length=128, verbose_name='用户机制名'),
        ),
    ]
