# Generated by Django 2.0.12 on 2019-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190624_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosecevent',
            name='attacker_descs',
        ),
    ]
