version: "2.2"

services:
   web:
      container_name: web-server
      restart: always
      build: ./whtv_web
      expose:
        - "8077"
      volumes:
        - ./whtv_web:/usr/src/app
      command: /usr/local/bin/gunicorn website.wsgi:application -w 2 -b :8077
      networks:
          customize_net:
            ipv4_address: 192.168.32.223
   celery:
     container_name: web-server
     restart: always
     build: ./whtv_web
     expose:
       - "8077"
     volumes:
       - ./whtv_web:/usr/src/app
     command: /usr/local/bin/celery website.wsgi:application -w 2 -b :8077
     networks:
       customize_net:
         ipv4_address: 192.168.32.223

   nginx:
      container_name: nginx
      restart: always
      build: ./nginx-container/
      ports:
        - "1080:80"
      volumes:
        - /home/django/xpm/collect_static:/home/django/xpm/collect_static
        - /srv/docker/logs/nginx:/var/log/nginx/
      networks:
          customize_net:
            ipv4_address: 192.168.33.99

networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24
