# Generated by Django 2.0.12 on 2019-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
